name: Build

on:
  push:
    branches: canary

jobs:
  build:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - windows-latest

    steps:
      - name: Check
        uses: actions/checkout@v2

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
          architecture: x64

      - name: Setup
        run: |
          pip install pip==21.1.3 pyinstaller==4.3 numpy==1.21.0 opencv-python==4.5.3.56 pillow==8.3.1
          pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
          PyInstaller main.py --name "cli"

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cli
          path: dist/cli/